# Generated by Django 5.0 on 2024-09-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kampaniya nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kampaniya logo')),
            ],
        ),
        migrations.CreateModel(
            name='HomeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sayt sarlavhasi')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Avatar rasmi')),
                ('video_link', models.CharField(max_length=300, verbose_name='Video linki')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('number', models.IntegerField(verbose_name='Foiz')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defaults', to='defaults.homedefault')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(blank=True, max_length=400, verbose_name='Linkedin')),
                ('instagram', models.CharField(blank=True, max_length=400, verbose_name='Instagram')),
                ('telegram', models.CharField(blank=True, max_length=400, verbose_name='Telegram')),
                ('facebook', models.CharField(blank=True, max_length=400, verbose_name='Facebook')),
                ('youtube', models.CharField(blank=True, max_length=400, verbose_name='Youtube')),
                ('fiverr', models.CharField(blank=True, max_length=400, verbose_name='Fiverr')),
                ('upwork', models.CharField(blank=True, max_length=400, verbose_name='Upwork')),
                ('phone_number', models.CharField(blank=True, max_length=400, verbose_name='Telefon Raqam')),
                ('email_address', models.CharField(max_length=400, verbose_name='email manzil')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='defaults.homedefault')),
            ],
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='', verbose_name='resume')),
                ('happy_clients', models.IntegerField(verbose_name='Hursand Mijozlar')),
                ('project_complate', models.IntegerField(verbose_name='Muvaffaqiyatli loyihalar')),
                ('experience', models.IntegerField(verbose_name='Tajriba')),
                ('static', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statics', to='defaults.homedefault')),
            ],
        ),
        migrations.DeleteModel(
            name='Defaults',
        ),
        migrations.AddField(
            model_name='company',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='defaults.homedefault'),
        ),
    ]
