# Generated by Django 5.0 on 2024-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0002_company_homedefault_skill_socialmarkets_static_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedefault',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='ism familiya'),
            preserve_default=False,
        ),
    ]
