# Generated by Django 5.0 on 2024-09-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0004_remove_static_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static',
            name='static',
        ),
    ]
