# Generated by Django 5.0 on 2024-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0006_rename_static_statics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='experience',
            field=models.BigIntegerField(verbose_name='Tajriba'),
        ),
        migrations.AlterField(
            model_name='statics',
            name='happy_clients',
            field=models.BigIntegerField(verbose_name='Hursand Mijozlar'),
        ),
        migrations.AlterField(
            model_name='statics',
            name='project_complate',
            field=models.BigIntegerField(verbose_name='Muvaffaqiyatli loyihalar'),
        ),
    ]
