# Generated by Django 5.0 on 2024-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0007_alter_statics_experience_alter_statics_happy_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmarkets',
            name='github',
            field=models.CharField(default='', max_length=400, verbose_name='Github'),
            preserve_default=False,
        ),
    ]
