# Generated by Django 5.0 on 2024-10-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0008_socialmarkets_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedefault',
            name='name',
        ),
    ]
