# Generated by Django 5.0 on 2024-10-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
