# Generated by Django 5.0.8 on 2024-08-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planstext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200, verbose_name='Rasm URL')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Sub Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Xizmat haqida')),
                ('why_choose_me', models.TextField(blank=True, null=True, verbose_name='Nega aynan men')),
                ('plans_text', models.TextField(blank=True, null=True, verbose_name='Tariflar haqida matn')),
                ('features', models.ManyToManyField(related_name='Xususiyatlar', to='portfolio.featurestext')),
                ('services_text', models.ManyToManyField(related_name='services', to='portfolio.servicetext', verbose_name='kichik qobiliyatlar')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(default=3, editable=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Premium', editable=False, max_length=255, verbose_name='Full Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Premium package price')),
                ('description', models.ManyToManyField(to='portfolio.planstext', verbose_name='Xizmat haqida - Premium')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_service', to='portfolio.service')),
            ],
        ),
        migrations.CreateModel(
            name='BasicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(default=1, editable=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Basic', editable=False, max_length=255, verbose_name='Full Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Basic package price')),
                ('description', models.ManyToManyField(to='portfolio.planstext', verbose_name='Xizmat haqida - Basic')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_service', to='portfolio.service')),
            ],
        ),
        migrations.CreateModel(
            name='StandardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(default=2, editable=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Standard', editable=False, max_length=255, verbose_name='Full Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Standard package price')),
                ('description', models.ManyToManyField(to='portfolio.planstext', verbose_name='Xizmat haqida - Standard')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_service', to='portfolio.service')),
            ],
        ),
    ]
