# Generated by Django 5.0 on 2024-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_filter_project_filter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', verbose_name='Post Haqida'),
            preserve_default=False,
        ),
    ]
