# Generated by Django 5.0.8 on 2024-08-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectfilter_project_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='title',
        ),
    ]
