# Generated by Django 5.0 on 2024-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='jobtitle',
            field=models.CharField(default='', max_length=200, verbose_name='Job Title'),
            preserve_default=False,
        ),
    ]
