# Generated by Django 5.0 on 2024-08-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_footer_text_project_footer_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ManyToManyField(to='portfolio.projectphotos', verbose_name='Rasmlar'),
        ),
    ]
