# Generated by Django 5.0 on 2024-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_comment_parent_comment_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(null=True, blank=True),
        )

    ]
