# Generated by Django 5.0 on 2024-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ManyToManyField(to='portfolio.projectphotos', verbose_name='Rasmlar'),
        ),
        migrations.AlterField(
            model_name='projectphotos',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
