# Generated by Django 5.0 on 2024-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_post_options_alter_comment_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Ism Familiya')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('logo', models.ImageField(upload_to='profile_logos')),
            ],
        ),
    ]
