# Generated by Django 5.0 on 2024-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_project_photo_alter_projectphotos_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='optimal_text',
        ),
        migrations.AddField(
            model_name='project',
            name='optimal_text',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
