# Generated by Django 5.0 on 2024-10-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_profile_age_alter_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Siz haqingizda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default='', max_length=200, verbose_name='Kasbingiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logos/'),
        ),
    ]
