# Generated by Django 5.0 on 2024-08-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_project_optimal_text_project_optimal_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='optimal_text',
        ),
        migrations.AddField(
            model_name='project',
            name='optimal_text',
            field=models.ManyToManyField(to='portfolio.projecttext', verbose_name='Hoqishiy tekslar'),
        ),
    ]
