# Generated by Django 5.0 on 2024-08-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_project_optimal_text_project_optimal_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.DeleteModel(
            name='ProjectPhotos',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
