# Generated by Django 5.0 on 2024-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_project_photo_delete_projectphotos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ManyToManyField(to='portfolio.projectphoto'),
        ),
    ]
