# Generated by Django 5.0 on 2024-08-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_projectphoto_remove_project_photo_project_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectphoto',
            old_name='image',
            new_name='photos',
        ),
    ]
