# Generated by Django 5.0 on 2024-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_project_photo_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ManyToManyField(to='portfolio.projectphoto'),
        ),
    ]
