# Generated by Django 5.0 on 2024-10-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
