# Generated by Django 5.0 on 2024-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_remove_project_photo_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='hashtag nomi:')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='hashtag',
            field=models.ManyToManyField(to='portfolio.tag'),
        ),
    ]
